experiment/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',
         views.home,
         name="home"),
    path('about/',
         views.about,
         name="about"),
    path('contact/',
         views.contact,
         name="contact"),
    path('experiments/checkForm',
         views.checkForm,
         name="checkForm"),
    path('experiments/',
         views.experiments,
         name="exp"),
    path('experiments/fof',
         views.fof,
         name="fof"),
    path('experiments/img',
         views.img,
         name="img"),
    path('experiments/remove',
         views.experimentsRemove,
         name='expRemove'),
    path('experiments/downloadInputFile',
         views.downloadInputFile,
         name='downloadInputFile'),
    path('experiments/downloadOutputFile',
         views.downloadOutputFile,
         name='downloadOutputFile'),
    path('experiments/result',
         views.result,
         name='result'),
    ]

fof/urls.py
from django.urls import path
from fof.views import fof, about

app_name = 'fofapp'
urlpatterns = [
    path('experiments', fof, name="fof"),
    path('about', about, name="about"),
]

image/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('experiments/image/wavelet',
         views.wavelet,
         name="wavelet"),
    ]

webfriends/urls.py
from . import regbackend
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

import fof
import image
import resulttable

urlpatterns = [
    path('', include('image.urls')),
    path('', include('resulttable.urls')),
    path('experiments/', views.table, name="experiments"),

    path('fof/', include('fof.urls', namespace='fofapp')),
    path('admin/', admin.site.urls),

    path('accounts/register/', regbackend.MyRegistrationView.as_view(),
         name='register_custom'),
    path('accounts/', include('registration.backends.default.urls')),

    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('', views.home, name="home"),

    path('register/complete/', TemplateView.as_view(template_name='registration/registration_complete.html'), name='registration_complete'),
    path('register/closed/',
         TemplateView.as_view(template_name='registration/registration_closed.html'),
         name='registration_disallowed'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

experiment/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.template import RequestContext
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth.models import User
from experiment.forms import ExecutionForm, ContactForm
from experiment.models import Execution, Algorithms, UsuarioFriends
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from jsonview.decorators import json_view
from crispy_forms.utils import render_crispy_form
from crispy_forms.helper import FormHelper
from .paginator import paginate
from experiment.tasks import RunExperiment


def home(request):
    if not request.user.is_authenticated:
        title = "Welcome"
        context = {
            "title": title
        }
        return render(request, "welcome.html", context)
    else:
        # res = teste.delay()
        # print(res)
        title = "Welcome %s" % request.user
        print((request.user.id))
        executionList = Execution.objects.filter(
            request_by__usuario__id=request.user.id).order_by('-id')
        try:
            UserProf = UsuarioFriends.objects.get(usuario__id=request.user.id)
        except:
            print("Erro. Criando novo userProf")
            user = User.objects.get(id=request.user.id)
            UserProf = UsuarioFriends(usuario=user)
            UserProf.save()
            print("Criado novo UserProf")
        paginator = Paginator(executionList, UserProf.resultsPerPage)
        page = request.GET.get('page')
        if page is None:
            page = 1
        try:
            executions = paginator.page(page)
        except PageNotAnInteger:
            executions = paginator.page(1)
        except EmptyPage:
            executions = paginator.page(paginator.num_pages)  # da pra tratar
        if paginator.count == 0:
            data = None
        else:
            data = executions
        pageI = paginate(page, paginator)
        context = {
            "title": title,
            "data": data,
            "pagesIndex": pageI,
        }
        return render(request, "home.html", context)


def about(request):
    return render(request, "about.html", {})


def downloadInputFile(request):
    expId = request.GET.get('id')
    execution = Execution.objects.get(pk=expId)

    # criar alerta
    response = HttpResponse(
        execution.inputFile, content_type='application/force-download')
    response[
        'Content-Disposition'] = 'attachment; filename="entrada-Experimento-' + str(expId) + '"'
    return response


def downloadOutputFile(request):
    expId = request.GET.get('id')
    execution = Execution.objects.get(pk=expId)
    if (execution.request_by.usuario.id == request.user.id):
        print((execution.outputFile.url))
        print("Autorizado")
        response = HttpResponse(
            execution.outputFile, content_type='application/force-download')
        response[
            'Content-Disposition'] = 'attachment; filename="Resultado-Experimento-' + str(expId) + '"'
        return response
    print("Não autorizado")
    # criar alerta
    return HttpResponseRedirect(reverse('home'))


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        subject = 'Portal Friends - Mensagem de %s ' % (
            form.cleaned_data.get("nome"))
        from_email = settings.EMAIL_HOST_USER  # da pra usar outro?
        to_email = from_email
        message = form.cleaned_data.get("mensagem")
        send_mail(subject,
                  message,
                  from_email,
                  [to_email],
                  fail_silently=False)
    context = {
        "form": form,
    }
    return render(request, "home.html", context)
# ajax


@json_view
@csrf_protect
def checkForm(request):
    form = ExecutionForm(request.POST or None)  # request POST?

    if form.is_valid():  # processa
        experiments(request)
        helper = FormHelper()
        helper.form_id = 'form_exec'
        helper.form_action = '.'
        form_html = render_crispy_form(ExecutionForm(None), helper)
        return HttpResponseRedirect('home')

    else:
        helper = FormHelper()
        helper.form_id = 'form_exec'
        request_context = RequestContext(request)
        form_html = render_crispy_form(form, context=request_context)
        return {'success': False, 'form_html': form_html}


@csrf_protect
def experiments(request):

    if request.method != 'POST':
        # form = ExecutionForm(request.POST, request.FILES or None)

        # if not form.is_valid():
        #     title = "Experiments %s" % (request.user)
        #     # form_html = render_crispy_form(form)
        #     context = {
        #         "form": form,
        #         'title': title
        #     }

        #     return render(request, "experiments.html", context)

        # algorithm = request.POST.get('Algorithm')
        # d_User = User.objects.get(username=request.user)
        # alg = Algorithms.objects.get(nameAlg=algorithm)
        # execution = Execution(
        #     request_by=d_User.usuariofriends,
        #     algorithm=alg,
        # )

        # execution.rperc = request.POST["Rperc"]
        # execution.save()

        # if (request.FILES):
        #     # print(request.FILES)
        #     fileIn = request.FILES["Input"]
        #     execution.inputFile = fileIn
        #     execution.save()
        #     queryInputFile = (
        #         settings.MEDIA_ROOT +
        #         execution.inputFile.name.replace('./', '/')
        #     ).replace(' ', '\ ')
        #     queryOutputFile = queryInputFile
        #     queryOutputFile = queryOutputFile.replace('input', 'output')
        #     query = alg.command + ' ' + queryInputFile + ' ' + execution.rperc + ' > ' + queryOutputFile

        # else:
        #     query = execution.algorithm.command

        # outputFilePath = './users/user_' + \
        #     str(execution.request_by.usuario.id) + \
        #     '/' + str(execution.id) + '/output'

        # teste = RunExperiment.delay(query, execution.id)
        # execution.save()
        title = "Experiments %s" % (request.user)

        return HttpResponseRedirect(reverse('home'))

    form = ExecutionForm(request.POST or None)
    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, "experiments.html", context)

@csrf_protect
def fof(request):

    if request.method == 'POST':
        form = FoFForm(request.POST, request.FILES or None)

        if not form.is_valid():
            title = "Experiments %s" % (request.user)
            # form_html = render_crispy_form(form)
            context = {
                "form": form,
                'title': title
            }

            return render(request, "experiments.html", context)

        algorithm = request.POST.get('Algorithm')
        d_User = User.objects.get(username=request.user)
        alg = Algorithms.objects.get(nameAlg=algorithm)
        execution = Execution(
            request_by=d_User.usuariofriends,
            algorithm=alg,
        )

        execution.rperc = request.POST["Rperc"]
        execution.save()

        if (request.FILES):
            # print(request.FILES)
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()
            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')
            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')
            query = alg.command + ' ' + queryInputFile + ' ' + execution.rperc + ' > ' + queryOutputFile

        else:
            query = execution.algorithm.command

        outputFilePath = './users/user_' + \
            str(execution.request_by.usuario.id) + \
            '/' + str(execution.id) + '/output'

        teste = RunExperiment.delay(query, execution.id)
        execution.save()
        title = "Experiments %s" % (request.user)

        return HttpResponseRedirect(reverse('home'))

    form = ExecutionForm(request.POST or None)
    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, "experiments.html", context)

@csrf_protect
def img(request):

    if request.method == 'POST':
        form = FoFForm(request.POST, request.FILES or None)

        if not form.is_valid():
            title = "Experiments %s" % (request.user)
            # form_html = render_crispy_form(form)
            context = {
                "form": form,
                'title': title
            }

            return render(request, "experiments.html", context)

        algorithm = request.POST.get('Algorithm')
        d_User = User.objects.get(username=request.user)
        alg = Algorithms.objects.get(nameAlg=algorithm)
        execution = Execution(
            request_by=d_User.usuariofriends,
            algorithm=alg,
        )

        execution.rperc = request.POST["Rperc"]
        execution.save()

        if (request.FILES):
            # print(request.FILES)
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()
            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')
            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')
            query = alg.command + ' ' + queryInputFile + ' ' + execution.rperc + ' > ' + queryOutputFile

        else:
            query = execution.algorithm.command

fof/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from fof.forms import FoFForm
from fof.models import FoFAlgorithm
from fof.tasks import RunFoFSerial
from resulttable.models import Execution

@csrf_protect
def fof(request):
    if request.method == 'POST':
        form = FoFForm(request.POST, request.FILES or None)
        if not form.is_valid():
            title = "Experiments %s" % (request.user)
            context = {
                "form": form,
                'title': title
            }
            return render(request, "fof/FoF.html", context)

        idAlg = request.POST.get('Algorithm')
        processos = request.POST.get('processos')
        kernels = request.POST.get('kernels')
        rperc = request.POST['Rperc']

        usuario = User.objects.get(username=request.user)
        alg = FoFAlgorithm.objects.get(idFoF=idAlg)

        execution = Execution(
            request_by=usuario.usuariofriends,
            algorithm = alg.nameFoF,
        )
        execution.save()

        #pega o arquivo de entrada:
        if(request.FILES):
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()

            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')

            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')

            print("Query input file:" + queryInputFile)
            print("Query output file:" + queryOutputFile)

            outputFilePath = settings.MEDIA_ROOT + 'users/user_' + str(execution.request_by.usuario.id) + '/' + str(execution.id) + '/'
            logFilePath = settings.MEDIA_ROOT + 'users/user_' + str(execution.request_by.usuario.id) + '/' + str(execution.id) + '/logfile'

        run = RunFoFSerial(alg.commandFoF, rperc, processos, kernels, execution.id, queryInputFile, outputFilePath, logFilePath)

        return HttpResponseRedirect(reverse('experiments'))

    form = FoFForm(request.POST or None)
    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, 'fof/FoF.html', context)

def about(request):
    query_results = FoFAlgorithm.objects.all()
    return render(request, 'fof/about.html', {"results" : query_results})

image/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from image.forms import WaveletForm
from image.tasks import WaveletExperiment
from resulttable.models import Execution
from webfriends.views import home


@csrf_protect
def wavelet(request):

    if request.method == 'POST':

        form = WaveletForm(request.POST, request.FILES or None)

        if not form.is_valid():
            title = "Experiments %s" % (request.user)

            context = {
                "form": form,
                "title": title
            }

            return render(request, "wavelet.html", context)

        d_User = User.objects.get(username=request.user)
        wavelet = request.POST.get("Wavelet")
        method = request.POST.get("Method")
        samount = request.POST.get("ShiftAmount")

        if method == 'visushrink':
            method = 'VisuShrink'
        else:
            method = 'BayesShrink'

        execution = Execution(
            request_by=d_User.usuariofriends
        )

        execution.save()

        if request.FILES:
            fileIn = request.FILES["Input"]
            execution.inputFile = fileIn
            execution.save()
            queryInputFile = (
                settings.MEDIA_ROOT +
                execution.inputFile.name.replace('./', '/')
            ).replace(' ', '\ ')
            queryOutputFile = queryInputFile
            queryOutputFile = queryOutputFile.replace('input', 'output')

        # Run Experiment

        outputFilePath = settings.MEDIA_ROOT + 'users/user_' + \
            str(execution.request_by.usuario.id) + \
            '/' + str(execution.id) + '/output.' + request.POST.get("Format")

        logFilePath = settings.MEDIA_ROOT + 'users/user_' + \
            str(execution.request_by.usuario.id) + \
            '/' + str(execution.id) + ".log"

        print(outputFilePath)

        run = WaveletExperiment.delay((wavelet, method, samount), request.user.email, queryInputFile, outputFilePath, logFilePath, execution.id)

        return HttpResponseRedirect(reverse('experiments'))

    form = WaveletForm(request.POST or None)

    title = "Experiments %s" % (request.user)
    context = {
        "title": title,
        "form": form
    }

    return render(request, "wavelet.html", context)

templates/FoF.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Friends of Friends Algorithm{%endblock%}

{% block content %}
	{% if request.user.is_authenticated %}
		<div id='row-form' class="row">
			<div id="colForm" class="col-sm-3 col-md-3"></div>
		  <div id="colForm" class="col-sm-6 col-md-6">
				  <form id='form_exec' method='POST' action='{% url "fof" %}' enctype="multipart/form-data">
				{% csrf_token %}
					{# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
						{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
					{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
					<input id='execute' class='btn btn-primary' type="submit" value="Executar">
				</form>
		  	</div>
		  	<div id="colForm" class="col-sm-3 col-md-3"></div>
		</div>
	{%else%}
		Faça o login para prosseguir
	{%endif%}
{%endblock%}

templates/about.html
{%extends "base.html" %}


{% block jumbotron %}
<div class="jumbotron">
  <h2>About</h2>
  <p>This Virtual Observatory allows remote execution of some applications in Astronomy.</p>
  <p>The portal offer parallel versions of the <b>Friends-of-Friends</b> algorithm for astronomical objects classification, and algorithms for image restoration using <b>wavelet filtering.</b>
The users can perform as many executions as they wants, and at the end of each they can download the output file and a log file.</p>
  <p>This project was originally developed by Otávio Migliavacca Madalosso in 2015 as a conclusion work in his graduation in Computer Science at Federal University of Santa Maria (UFSM).
Currently, this is being continued by Ana Solórzano and Vinícius Monego.</p>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title%}{%endblock%}</title>
    {% include 'head_css.html'%}

    <script>
      function test() {
          if (document.getElementById('id_Algorithm').value == '2') {
              document.getElementById('extra').style.display = 'block';
              document.getElementById('extra2').style.display = 'none';
          } else if (document.getElementById('id_Algorithm').value == '3'){
              document.getElementById('extra').style.display = 'block';
              document.getElementById('extra2').style.display = 'block';
          }else {
              document.getElementById('extra').style.display = 'none';
              document.getElementById('extra2').style.display = 'none';
          }
      }
     </script>


    </head>

  <body>
   {% load staticfiles %}
    {% include 'navbar.html' %}

      {% block messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable"
                 style="padding: 5px; width: 20%; float:right; text-align: center;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endblock messages %}

    <div style="margin-bottom:50px;padding-top:10px;" class="container">

        {% block jumbotron %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>


    <div class="container-fluid">
      <div class="row">
      {% block container %}
      {% endblock %}
      </div>
    </div>

    {% include "javascript.html" %}

  </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}Contact{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-3 col-sm-3"></div>
  <div class="col-sm-6 col-md-6 center-block">
    <form method="POST" action=".">{% csrf_token %}
      {{form|crispy}}
      <p style="text-align: center" class="lead">
        <input class='btn btn-primary center-block' type="submit" value="Send"></p>
    </form>
  </div>
  <div class="col-md-3 col-sm-3"></div>
</div>

{% endblock %}

templates/experiments.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}FoF{%endblock%}

{% block content %}
{% if request.user.is_authenticated %}
<div id='row-form' class="row">
  <div id="colForm" class="col-sm-3 col-md-3"></div>
  <div id="colForm" class="col-sm-6 col-md-6">
    <form id='form_exec' method='POST' action='.' enctype="multipart/form-data">
      {% csrf_token %}
      {# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
	{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
	{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
      <input id='execute' class='btn btn-primary' type="submit" value="Executar">
    </form>
  </div>
  <div id="colForm" class="col-sm-3 col-md-3"></div>
</div>
{%else%}
Faça o login para prosseguir
{%endif%}
{%endblock%}

templates/footer.html
<footer class="footer">
<div class="container">
			<div class="row text-center text-xs-center text-sm-left text-md-left" style="padding-top:10px;padding-bottom:10px">
				<div class="col-xs-10 col-sm-4 col-md-4" >
					<h5>Menu</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="{% url 'home' %}">Home</a></li>
						<li><a href="{% url 'about' %}">About</a></li>
						<li><a href="{% url 'fofapp:about' %}">FoF</a></li>
						<li><a href="{% url 'wavelet' %}">Wavelet</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Documentation</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="link">link</a></li>
						<li><a href="link">link</a></li>
						<li><a href="link">link</a></li>
					</ul>
				</div>
                <div class="col-xs-12 col-sm-4 col-md-4">
					<ul class="list-unstyled list-inline social text-center">
                        <h5>Contact us</h5><br/>
						<li class="list-inline-item"><a href="{% url 'contact' %}"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
			</div>
		</div>

  <div class="container">
    <p class="text-muted text-center">Otávio Madalosso, Ana Solórzano and Vinícius Monego</p>
    <p class="text-muted text-center">2015</p>
  </div>
</footer>

templates/forms.html
<form method="POST" action=".">{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Enviar">
</form>

templates/head_css.html
{% load staticfiles %}
{% block head_css %}
    <!-- Bootstrap core CSS -->
    <link href="https://unpkg.com/bootstrap@4.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/footer.css'%}" rel="stylesheet">
{% endblock %}

templates/image.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Remoção de Ruído em Imagens{%endblock%}

{% block content %}
	{% if request.user.is_authenticated %}
		<div id='row-form' class="row">
			<div id="colForm" class="col-sm-3 col-md-3"></div>
		  <div id="colForm" class="col-sm-6 col-md-6">
				  <form id='form_exec' method='POST' action='{% url "image" %}' enctype="multipart/form-data">
				{% csrf_token %}
					{# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
						{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
					{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
					<input id='execute' class='btn btn-primary' type="submit" value="Executar">
				</form>
		  	</div>
		  	<div id="colForm" class="col-sm-3 col-md-3"></div>
		</div>
	{%else%}
		Faça o login para prosseguir
	{%endif%}
{%endblock%}

templates/javascript.html
    {% load staticfiles %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://unpkg.com/jquery@3.3.1/dist/jquery.min.js"></script>
    <script src="https://unpkg.com/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/js-cookie@2.2.0/src/js.cookie.js"></script>
    <script src="https://unpkg.com/popper.js@1.14.3/dist/umd/popper.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/experiment.js' %}"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script> -->

templates/navbar.html
<!-- Static navbar -->
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home' %}">Web portal</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="navbar-nav mr-auto">
	  <li class="nav-item">
	  <a class="nav-link" href="{% url 'about' %}">About</a>
	  {% if request.user.is_authenticated %}
	  <li class="nav-item">
	  <a class="nav-link" href="{% url 'experiments' %}">Experiments</a>
		<li class="nav-item">
		  <div class="dropdown">
			<button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Friends-of-Friends</button>
			  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<a class="dropdown-item" href="{% url 'fofapp:fof' %}">Run</a>
				  <a class="dropdown-item" href="{% url 'fofapp:about' %}">About</a>
			  </div>
		 </div>

	<li class="nav-item">
	  <div class="dropdown">
	    <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Images</button>
	    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
	      <a class="dropdown-item" href="{% url 'wavelet' %}">Wavelet</a>
	    </div>
	  </div>
	  {% endif %}
      </ul>

      <ul class="navbar-nav ml-auto">
	{% if request.user.is_authenticated %}
	<li class="nav-item mr-sm-2">
	  <a>{{user}}</a>
	<li class="nav-item mr-sm-2">
	  <a href="{% url 'auth_logout' %}">Sair</a>
	{% else %}
	<li class="active mr-sm-2"><a href="{% url 'registration_register' %}">Sign up</a></li>
	{% endif %}
      </ul>

      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
      <form class="form-inline" method="POST" action="{% url 'auth_login' %}">{%csrf_token%}
	<div class="form-group">
	  <input type="text" class="form-control mr-sm-2" name="username" placeholder="Username">
	</div>
	<div class="form-group">
	  <input type="password" class="form-control mr-sm-2" name="password" placeholder="Password">
	</div>
	<button type="submit" class="btn btn-default">Sign in</button>
      </form>
      {%endif%}
    </div><!--/.nav-collapse -->
  </div>
</nav>

templates/wavelet.html
{%extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% crispy form %}

{% block head_title%}Remoção de Ruído em Imagens via Transformada Wavelet{%endblock%}

{% block content %}
{% if request.user.is_authenticated %}
<div id='row-form' class="row">
  <div id="colForm" class="col-sm-3 col-md-3"></div>
  <div id="colForm" class="col-sm-6 col-md-6">
    <form id='form_exec' method='POST' action='{% url "wavelet" %}' enctype="multipart/form-data">
      {% csrf_token %}
      {# <div id="formContent"> Necessario para nao bugar com erro de validacao do crispy #}
	{{form|crispy}}    {# Crispy que falha nao retorna formulario com o csrf_token  #}
	{# </div>				   Isso ocasionava um erro de acesso. (gambiarra no javascript) #}
      <input id='execute' class='btn btn-primary' type="submit" value="Run">
    </form>
  </div>
  <div id="colForm" class="col-sm-3 col-md-3"></div>
</div>
{%else%}
Faça o login para prosseguir
{%endif%}
{%endblock%}